# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/posters', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Poster. As you add validations to Poster, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Poster.create! valid_attributes
      get posters_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      poster = Poster.create! valid_attributes
      get poster_url(poster)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_poster_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      poster = Poster.create! valid_attributes
      get edit_poster_url(poster)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Poster' do
        expect do
          post posters_url, params: { poster: valid_attributes }
        end.to change(Poster, :count).by(1)
      end

      it 'redirects to the created poster' do
        post posters_url, params: { poster: valid_attributes }
        expect(response).to redirect_to(poster_url(Poster.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Poster' do
        expect do
          post posters_url, params: { poster: invalid_attributes }
        end.to change(Poster, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post posters_url, params: { poster: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested poster' do
        poster = Poster.create! valid_attributes
        patch poster_url(poster), params: { poster: new_attributes }
        poster.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the poster' do
        poster = Poster.create! valid_attributes
        patch poster_url(poster), params: { poster: new_attributes }
        poster.reload
        expect(response).to redirect_to(poster_url(poster))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        poster = Poster.create! valid_attributes
        patch poster_url(poster), params: { poster: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested poster' do
      poster = Poster.create! valid_attributes
      expect do
        delete poster_url(poster)
      end.to change(Poster, :count).by(-1)
    end

    it 'redirects to the posters list' do
      poster = Poster.create! valid_attributes
      delete poster_url(poster)
      expect(response).to redirect_to(posters_url)
    end
  end
end
